course_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('django.contrib.auth.urls')),

    path("admin/", admin.site.urls),
    path("", include("mail.urls", namespace="mail")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail/urls.py
from django.urls import path, include

from mail.views import (
    HomeView,
    RecipientCreateView,
    RecipientView,
    RecipientDetailView,
    RecipientUpdateView,
    RecipientDeleteView,
    MessageCreateView,
    MessageDeleteView,
    MessageUpdateView,
    MessageDetailView,
    MessageView,
    SendingView,
    SendingCreateView,
    SendingDeleteView,
    SendingDetailView,
    SendingUpdateView,
    SendMessage,
SendMessageCancel
)
from mail.apps import MailConfig

app_name = MailConfig.name

urlpatterns = [
    path("home/", HomeView.as_view(), name="home"),
    path("recipients/", RecipientView.as_view(), name="recipients"),
    path("recipient/<int:pk>/", RecipientDetailView.as_view(), name="recipient"),
    path("recipients/create/", RecipientCreateView.as_view(), name="recipient-create"),
    path(
        "recipients/update/<int:pk>/",
        RecipientUpdateView.as_view(),
        name="recipient-update",
    ),
    path(
        "recipient/delete/<int:pk>/",
        RecipientDeleteView.as_view(),
        name="recipient-delete",
    ),
    path("messages/", MessageView.as_view(), name="messages"),
    path("message/<int:pk>/", MessageDetailView.as_view(), name="message"),
    path("message/create/", MessageCreateView.as_view(), name="message-create"),
    path(
        "message/update/<int:pk>/", MessageUpdateView.as_view(), name="message-update"
    ),
    path(
        "message/delete/<int:pk>/", MessageDeleteView.as_view(), name="message-delete"
    ),
    path("sendings/", SendingView.as_view(), name="sendings"),
    path("sending/<int:pk>/", SendingDetailView.as_view(), name="sending"),
    path("sending/create/", SendingCreateView.as_view(), name="sending-create"),
    path(
        "sending/update/<int:pk>/", SendingUpdateView.as_view(), name="sending-update"
    ),
    path(
        "sending/delete/<int:pk>/", SendingDeleteView.as_view(), name="sending-delete"
    ),
    path("sending/send/<int:pk>/", SendMessage.as_view(), name="send-message"),
    path("sending/cancel/<int:pk>/", SendMessageCancel.as_view(), name="send-message-cancel"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    NewPasswordResetCompleteView,
    NewPasswordResetConfirmView,
    NewPasswordResetDoneView,
    NewPasswordResetView,
    UserRegisterView,
    verification_email,
    UserDetailView,
    UserUpdateView,
    UserDeleteView
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("email-confirm/<str:token>/", verification_email, name="email-confirm"),
    path("password-reset/", NewPasswordResetView.as_view(), name="password_reset"),
    path(
        "password-reset/done/",
        NewPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset/confirm/<str:uidb64>/<str:token>/",
        NewPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        NewPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("<int:pk>/", UserDetailView.as_view(), name="user-detail"),
    path("update/<int:pk>", UserUpdateView.as_view(), name="user-update"),
    path("delete/<int:pk>",UserDeleteView.as_view(), name="user-delete"),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    """Переопределение модели User."""

    username = None
    avatar = models.ImageField(
        upload_to="users/avatars/", blank=True, null=True, verbose_name="Аватар"
    )
    email = models.EmailField(verbose_name="Электронная почта", unique=True)
    token = models.CharField(unique=True, blank=True, null=True)
    amount_attempt = models.IntegerField(
        verbose_name="Количество попыток расыли", default=0
    )
    amount_failed = models.IntegerField(
        verbose_name="Количество не успешных попыток", default=0
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from users.models import User


class UserRegisterForm(UserCreationForm):
    """Форма регистрации нового пользователя."""

    class Meta:
        model = User
        fields = ["email", "password1", "password2", "avatar"]

class UserUpdateForm(ModelForm):

    class Meta:
        model = User
        fields = ["avatar"]

users/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView

from course_django.settings import EMAIL_HOST_USER

from users.forms import UserRegisterForm, UserUpdateForm
from users.models import User


class UserRegisterView(CreateView):
    """Регистрация нового пользователя."""

    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        """Сохраняет нового пользователя и отправляет письмо с информацией о регистрации."""
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}/"
        self.send_welcome_email(user.email, url)
        return super().form_valid(form)

    def send_welcome_email(self, user_email, path):
        """Отправляет письмо с приветствием и информацией о регистрации."""
        subject = "Добро пожаловать в наш сервис"
        message = f"Спасибо, что   в нашем сервисе! Для подтверждения перейдите по ссылке {path}"
        from_email = EMAIL_HOST_USER
        recipient_list = [user_email]
        send_mail(subject, message, from_email, recipient_list)


def verification_email(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class NewPasswordResetView(PasswordResetView):
    success_url = reverse_lazy("users:password_reset_done")
    template_name = "password-reset.html"
    email_template_name = "password_reset_email.html"


class NewPasswordResetDoneView(PasswordResetDoneView):
    success_url = reverse_lazy("users:login")
    template_name = "reset_done_password.html"


class NewPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy("users:password_reset_complete")
    template_name = "password_reset_confirm.html"


class NewPasswordResetCompleteView(PasswordResetCompleteView):
    success_url = reverse_lazy("users:password_reset_complete")
    template_name = "password_reset_complete.html"


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'user_detail.html'


    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser or self.request.user == self.object:
            return self.object
        raise PermissionDenied


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy("mail:home")


    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser or self.request.user == self.object:
            return self.object
        raise PermissionDenied

class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = User


    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.is_superuser:
            raise PermissionDenied
        if not self.request.user.is_superuser:
            raise PermissionDenied
        return self.object

users/templates/login.html
{% extends 'mail/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
            <form class="row" method="POST" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary ">
                            Войти
                        </button>
                        <p><a href="{% url "users:password_reset" %}">Забыли пароль?</a></p>

                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/password-reset.html
{% extends 'mail/base.html' %}

{% block title %}Сброс Пароля{% endblock %}

{% block content %}
    <h1>Сброс пароля</h1>
        <form action="" method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Сбросить пароль"/></p>
        </form>
{% endblock %}

users/templates/password_change_form.html
{% extends 'mail/base.html' %}

{% block title %}Change you password{% endblock %}

{% block content %}
    <h1>Change you password</h1>
    <p>Use the form below to change your password.</p>
    <form action="" method="post">
        {{ form.as_p }}
        <p><input type="submit" value="Change"></p>
        {% csrf_token %}
    </form>
{% endblock %}

users/templates/password_reset_complete.html
{% extends 'mail/base.html' %}

{% block title %}Password reset{% endblock %}

{% block content %}
    <h1>Password set</h1>
    <p>Your password has been set. You can <a href="{% url "users:login" %}">log in now</a></p>
{% endblock %}

users/templates/password_reset_confirm.html
{% extends 'mail/base.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}

    <h1>Reset your password В жопу</h1>
    {% if validlink %}
        <p>Please enter your new password twice:</p>
        <form action="" method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Change my password"/></p>
        </form>
    {% else %}
        <p>The password reset link was invalid, possibly because it has
            already been used. Please request a new password reset.</p>
    {% endif %}
{% endblock %}

users/templates/password_reset_email.html
Кто-то попросил сбросить пароль для электронной почты {{ email }}.
Перейдите по ссылке ниже:{{ protocol }}://{{ domain }}{% url "users:password_reset_confirm" uidb64=uid token=token %}
Ваш email для входа, если вы забыли: {{ email }}

users/templates/reset_done_password.html
{% extends 'mail/base.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
    <h1>в жопу </h1>
    <p>We've emailed you instructions for setting your password.</p>
    <p>If you don't receive an email, please make sure you've entered the address you registered with.</p>
{% endblock %}

users/templates/user_detail.html
{% extends 'mail/base.html' %}
{% load image_tags %}
{% block title %}{{ object.email }}{% endblock %}
{% block content %}
    <div class="container py-3">
        <div class="text-center">
            <div class="col">
                <div class="card-header py-3">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                    <img class="rounded" width="200" height="200" src="{{ object.avatar | image_path }}" alt="{{ object.name }}" class="card-img-top" size="200px">
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.email }}<small
                            class="text-body-secondary fw-light"> </small></h1>
                    <h3 class="card-title pricing-card-title"> Количество попыток рассылки:  {{ object.amount_attempt }}<small
                            class="text-body-secondary fw-light"> </small></h3>

                    <h3 class="card-title pricing-card-title"> Количество неудачных попыток рассылки:   {{ object.amount_failed }}<small
                            class="text-body-secondary fw-light"> </small></h3>

                    <a type="button" class="btn btn-primary " href="{% url 'users:user-update' object.pk %}"> Изменить пользователя </a>
                    {% if user.is_superuser %}
                    <a type="button" class="btn btn-primary " href="{% url 'users:user-delete' object.pk %}"> Удалить </a>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}